# Generated by Django 4.0.2 on 2022-02-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_alter_internship_reg_date_alter_leave_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_team',
            name='team_count',
            field=models.IntegerField(default=0),
        ),
    ]
